# Foundations

***For a much more in depth overview of the foundations of deep learning, please refer to these free resources:***

***http://cs224d.stanford.edu/lecture_notes/LectureNotes3.pdf ***

***http://cs231n.github.io/***

***http://neuralnetworksanddeeplearning.com***

***http://www.deeplearningbook.org/***


### Contents
* [Neurons](#Neurons)

* [A Single Layer of Neurons](#A-Single-Layer-of-Neurons)

* [Feed-forward Computation](#Feed-forward-Computation)

* [Classification Example](#Classification-Example)

* [Objective Functions](#Objective-Functions)

    * [Softmax Classifier](#Softmax-Classifier)

    * [Cross-entropy loss function](#Cross-entropy-loss-function)

* [Gradient Decent and Back Propagation](#Gradient-Decent-and-Back-Propagation)

    * [Optimization](#Optimization)
    * [Backprop via the Chain Rule](#Backprop-via-the-Chain-Rule)

## Neurons

A neuron is a singular computational unit that takes *n* inputs and produces a single output.

This unit takes an n-dimensional input vector ***x*** and produces the scalar activation (output) ***a***. This neuron is also associated with an n-dimensional weight vector, ***w***, and a bias scalar, ***b***. These neurons are sometimes referred to as units. 

What differentiates the outputs of different neurons is their parameters (also referred to as their weights). 

Below, we have a unit called a ReLU, a *rectified linear unit*. Note: There exist many types of units: tahn, sigmoid, etc. ReLU will be the main unit referred to simply because it's the most popular

$$
a = max \left(0, w^T \cdot x + b \right) \\
$$

$$
y = f\left(
\begin{bmatrix}
    w_{1}       & w_{2} & \dots & w_{n}
\end{bmatrix}
\begin{bmatrix}
    x_{1}  \\
    x_{2} \\
    \vdots \\
    x_{n}
\end{bmatrix} + b \right) = max \left(0, \begin{bmatrix}
    w_{1}       & w_{2} & \dots & w_{n}
\end{bmatrix}
\begin{bmatrix}
    x_{1}  \\
    x_{2} \\
    \vdots \\
    x_{n}
\end{bmatrix} + b \right) = max \left(0,  \sum_i{w_ix_i + b} \right)
$$

<img src='files/neuron.jpeg'>

### Notes
* Put the introduction of the weight vector with the discussion that it is the parameters.
* might want to give the definition of the ReLU here since it is being introduced with other functions that are more commonly known.
* While it's clear to us how the equation makes sense in matrix notation, it might be nice to have a graphical view of that similar to the equation I added.
* $a$ isn't in the diagram and is therefore confusing in the equation
* When putting parenthesis in your equations, they automatically scale and look better if you use \left( and \right)
* The relationship between the matrix notation and summation notation is a nice place to mention where BLAS and GPU can help speed things up if you want to go down that road.
* The above image seems at odds with the image below where we are to assume that the activation function is part of the neuron circle. We should figure out a consistent way to pictorally represent things.

In [1]:
# single nueron example
import numpy as np
np.random.seed(123)

# forward-pass of a 3-layer neural network:
# activation function
def ReLU(x):
    return np.maximum(0.0, x)

# define our variables
#---------------------
#This doesn't fit with the image above. W should be the same dimensionality as x
#I chaned it to 3 instead of 1 so that the cell executes.
#----------------------
W1 = np.random.randn(3)
b1 = np.random.randn(1)

# random input vector of three numbers (3x1)
#---------------------
#This was a single random number, so I updated it to be 3
#----------------------
x = np.random.randn(3)

# calculate first hidden layer activations (3x1)
#-------------------------
# We should be careful about what we can an activation. This is labeled as the output above.
#-------------------------
out = ReLU( np.dot(W1, x) + b1)

print(out) 
#0.69013533

[ 0.08220609]


## A Single Layer of Neurons

We extend the idea above to a layer containing $m$ neurons. In the below image, the subscript on $w$ represents a row in the weight matrix.

<img src='files/single_layer.png'>

Now the equation to get from the inputs to the outputs gains an extra dimension to account for the $m$ neurons in the layer.

$$
\begin{bmatrix}
    y_{0}  \\
    x_{1} \\
    \vdots \\
    y_{m}
\end{bmatrix} = f\left(
\begin{bmatrix}
    w_{0,0}       & w_{0,1} & \dots & w_{0,n} \\
    w_{1,0}       & w_{1,1} & \dots & w_{1,n} \\
    \vdots       & \vdots & \dots & \vdots \\
    w_{m,0}       & w_{m,1} & \dots & w_{m,n} \\
\end{bmatrix}
\begin{bmatrix}
    x_{0}  \\
    x_{1} \\
    \vdots \\
    x_{n}
\end{bmatrix} + 
\begin{bmatrix}
    b_{0}  \\
    b_{1} \\
    \vdots \\
    b_{m}
\end{bmatrix} \right) = 
f\left(
\begin{bmatrix}
    \Theta_{0}  \\
    \Theta_{1} \\
    \vdots \\
    \Theta_{m}
\end{bmatrix}\right)
$$
or more compactly
$$
y = f\left(wx + b\right) = max\left(0, wx + b\right)
$$

## Multiple Layers of Neurons

## Note
I might suggest we change the notation in the below image to make the notation consistent with the math that you are trying to describe below.

We extend the idea above to multiple neurons by considering the case where the input ***x*** is fed as an input to multiple such neurons

<img src='files/onelayer.png'>


If we refer to the different neurons’ weights as $\{w^{(1)}, w^{(2)}, \cdots, w^{(m)}\}$ ,

the biases as $\{b^{(1)}, b^{(2)}, \cdots, b^{(m)}\}$,

we can say the respective activations are $\{a^{(1)}, a^{(2)}, \cdots, a^{(m)}\}$

$$ a^{(1)} = max(0, w^{(1)T} \cdot x + b_1) \\
    a^{(2)} = max(0, w^{(2)T} \cdot x + b_2) \\
    \vdots \\
    a^{(m)} = max(0, w^{(m)T} \cdot x + b_m)
$$

Here are some simple notations that let us define more complex networks

$$b =
\begin{bmatrix}
 b_1\\
 b_2\\
 \vdots \\
 b_m
\end{bmatrix} \in {\Bbb R^{m}}$$

$$W =
\begin{bmatrix}
 - & w^{(1)} & -\\
 - & w^{(2)} & -\\
 - & \vdots  & -\\
 - & w^{(m)} & -
\end{bmatrix}  \in {\Bbb R^{mxn}}$$

The ouput of the scaing and biases looks like $$ z = Wx + b $$

The activations of the ReLU function can then be written as:


$$ReLU(z) =
\begin{bmatrix}
 max(0, z^{(1)})\\
 max(0, z^{(2)})\\
 \vdots\\
max(0, z^{(m)})
\end{bmatrix}$$



$$
\begin{bmatrix}
 a^{(1)}\\
 a^{(2)}\\
 \vdots\\
 a^{(m)}
\end{bmatrix} = ReLU(z) = ReLU(Wx+b)$$

One can think of these activations as indicators of the presence of some weighted combination of features. We can then use a combination of these activations to perform classification/regression tasks.

## Feed-forward Computation

Neural Networks being organized into layers makes it very simple and efficient to evaluate using matrix vector operations. Here is an example of a full forward pass with three matrix multiplications with the application of an activation function

In [2]:
import numpy as np
np.random.seed(13)

# forward-pass of a 3-layer neural network
# activation function
def ReLU(x):
    return np.maximum(0.0,x)

#---------------------
#It might be helpful to have an image to go along with the neural net you build here
#That will allow people to connect the code to the image
#Do you think it would be better to define the input first so the reader knows why we are using
#the dimensions given below?
#---------------------
# define our variables
W1 = np.random.randn(3,)
b1 = np.zeros(3,)
W2 = np.random.randn(3,)
b2 = np.zeros(3,)
W3 = np.random.randn(3,)
b3 = np.zeros(1,)

# random input vector of three numbers (3x1)
x = np.random.randn(3, 1)

# calculate first hidden layer activations (3x1)
h1 = ReLU( np.dot(W1, x) + b1)

# calculate second hidden layer activations (3x1)
h2 = ReLU(np.dot(W2, h1) + b2)

# output neuron (1x1)
out = np.dot(W3, h2) + b3

print(out)
# 1.77187778

# MXNet 3 layer network equivalent
#data = mx.symbol.Variable('data')
#fc1  = mx.symbol.FullyConnected(data = data, name='fc1', num_hidden=3)
#act1 = mx.symbol.Activation(data = fc1, name='relu1', act_type="relu")
#fc2  = mx.symbol.FullyConnected(data = act1, name = 'fc2', num_hidden = 3)
#act2 = mx.symbol.Activation(data = fc2, name='relu2', act_type="relu")
#fc3  = mx.symbol.FullyConnected(data = act2, name = 'fc2', num_hidden = 1)

[ 1.77187778]


## Classification Example

One way to look at Neural Networks with fully-connected layers is that they define a family of functions that are parameterized by the weights of the network. An easy way to view this is through classification

The first component of this approach is to define the score function that maps the pixel values of an image to confidence scores for each class

#### Training set

Our training set is a dataset of images: $x_i \in R^{D}$ with labels $y_i$ $(i=1...N\ and\ y_i\in1…K)$. We have $N$ examples (each with a dimensionality $D$) and $K$ distinct categories. $N = 50,000$ images, each with $D = 32 \text{ pixels } \times 32 \text{ pixels } \times 3 \text{ color channels } = 3072$, and $K= 10$, since there are 10 distinct classes (dog, cat, car, etc).

#### Scoring function
We will now define the score function, $f:R^{D}\rightarrow R^{K}$, that maps the raw image pixels to class scores:

$f(x_i,W,b)=Wx_i+b$

$x_i$ has all of its pixels flattened out to a single column vector of shape [$D$ x 1]. The matrix $W$ (of size [$K$ x $D$]), and the vector $b$ (of size [$K$ x $1$]) are the parameters (people use the terms weights and parameters interchangeably) of the function.

<img src='files/imagemap.jpeg'>

<font color="red">
It might be nice to mention before the end that we are looking at data that can only be a cat, dog, or ship. This way the image won't confuse people on where these labels come from.</font>

In [3]:
import numpy as np
np.random.seed(13)

# define our variables
W1 = np.random.randn(3,4)
b1 = np.zeros(3,)
cat_picture = np.random.randn(4, 1)

# calculate scores (3x1)
scores = np.dot(W1, cat_picture).T + b1

print(scores)
# [[-0.48165915  2.13458226 -0.03466199]]

[[-0.48165915  2.13458226 -0.03466199]]


## Objective Functions

The above code predicted that our fictitious cat picture was most likely a dog. This is not the desired behavior of our classifier. We need a way to let the classifier know when it is performing well and when it is making poor predictions. To achieve this, the idea of correctness must be transformed into a mathematical function. Like most machine learning models, neural networks also use an optimization objective, a measure of error or goodness which we want to minimize or maximize respectively.

### Softmax Classifier

The Softmax classifier is the binary Logistic Regression <font color='red'> We haven't introduced binary logistic regression yet. This might not be a helpful analogy</font> generalization to multiple classes

Easy to interpret the output (normalized class probabilities)

$ f_j(z) = \dfrac{e^{z_j}}{\sum_ke^{z_k}} $

It takes a vector of arbitrary real-valued scores (in z) and squashes it to a vector of values between zero and one that sum to one.


In [4]:
#-----------------
#It would be nice to use the same values as above so that the user can see how the 
#softmax has altered the previous output.
#-----------------
import numpy as np
np.random.seed(1)

# define our softmax function
def softmax(z):
    return np.exp(z) / np.sum(np.exp(z), axis=1, keepdims=True)

# define our variables
W1 = np.random.randn(3,4)
b1 = np.random.randn(3,)
cat_picture = np.random.randn(4, 1)

# calculate scores (1x3)
scores = np.dot(W1, cat_picture).T + b1

# calculate softmax
softmax(scores)

# mxnet 3 layer network equivalent
#data = mx.symbol.Variable('data')
#fc1  = mx.symbol.FullyConnected(data = data, name='fc1', num_hidden=3)
#mlp = mx.symbol.SoftmaxOutput(data=fc1, name='softmax')


array([[ 0.23639688,  0.09442378,  0.66917934]])

### Cross-entropy loss function

*also referred to as minimizing the negative log liklihood*

$L_i = -log\Bigg(\dfrac{e^{f_{yi}}}{\sum_je^{f_{j}}}\Bigg)$

$f_j$ to mean the $j$-th element of the vector of class scores $f$. The full loss for the dataset is the mean of $L_i$

The cross-entropy between a “true” distribution $p$ and an estimated distribution $q$ is defined as

$H(p,q) = -\sum p(x)\log q(x)$

The Softmax classifier is hence minimizing the cross-entropy between the estimated class probabilities and the “true” distribution (also equivalent to minimizing the KL divergence between the two distributions).

In the probabilistic interpretation, we are therefore minimizing the negative log likelihood of the correct class, which can be interpreted as performing Maximum Likelihood Estimation (MLE)

<font color="red">There is a lot being thrown at the user here without a rigorous proof. Is this information essential to moving forward?</font>

**TODO(krzum) introduce regularization**

<img src='files/svmvssoftmax.png'>

Softmax classifier provides “probabilities”, rather confidences, for each class


In [10]:
def softmax(z):
    return np.exp(z) / np.sum(np.exp(z), axis=1, keepdims=True)
print np.exp([-2.85,0.86,0.28])
print np.exp([-2.85,0.86,0.28]) / np.sum(np.exp([-2.85,0.86,0.28]), axis=0, keepdims=True)

[ 0.05784432  2.36316069  1.32312981]
[ 0.01544932  0.63116335  0.35338733]


In [18]:
import numpy as np
np.random.seed(13)

# define our softmax function
#softmax normalizes all inputs between 0 and 1
def softmax(z):
    return np.exp(z) / np.sum(np.exp(z), axis=1, keepdims=True)

#cross entropy is a measure of distance between predictions and actual
def cross_entropy(pred, truth):
    return np.sum(np.nan_to_num(-truth*np.log(pred)-(1-truth)*np.log(1-pred)))

# define our variables
W1 = np.random.randn(3,4)
b1 = np.zeros(3,)
cat_picture = np.random.randn(4, 1)
truth = np.array([0,1,0]).astype('int32')

# calculate scores (1x3)
scores = np.dot(W1, cat_picture).T + b1

# calculate softmax
probs = softmax(scores)

# calculate loss
loss = cross_entropy(probs,truth)

print("ground-truth data: {}".format(truth))
print("softmax probabilities: {}".format(probs))
print('np.log(probs)' +str(np.log(probs)))
print("cross-entropy loss: {}".format(loss))
print()
#ground-truth data: [0 1 0]
#softmax probabilities: [[ 0.06154678  0.84221806  0.09623515]]
#cross-entropy loss: 0.3364246643429195

truth = np.array([1,0,0]).astype('int32')
print("ground-truth data: {}".format(truth))
print("softmax probabilities: {}".format(probs))
print('np.log(probs)' +str(np.log(probs)))
loss = cross_entropy(probs,truth)
print("cross-entropy loss: {}".format(loss))
print()

truth = np.array([0,0,1]).astype('int32')
print("ground-truth data: {}".format(truth))
print("softmax probabilities: {}".format(probs))
print('np.log(probs)' +str(np.log(probs)))
loss = cross_entropy(probs,truth)
print("cross-entropy loss: {}".format(loss))


# mxnet 3 layer network equivalent showing SoftmaxOutput
#data = mx.symbol.Variable('data')
#fc1  = mx.symbol.FullyConnected(data = data, name='fc1', num_hidden=3)
#softmax_output = mx.symbol.SoftmaxOutput(data=fc1, name='softmax')

ground-truth data: [0 1 0]
softmax probabilities: [[ 0.06154678  0.84221806  0.09623515]]
np.log(probs)[[-2.78795772 -0.17171631 -2.34096056]]
cross-entropy loss: 0.336424664343
()
ground-truth data: [1 0 0]
softmax probabilities: [[ 0.06154678  0.84221806  0.09623515]]
np.log(probs)[[-2.78795772 -0.17171631 -2.34096056]]
cross-entropy loss: 4.73568515732
()
ground-truth data: [0 0 1]
softmax probabilities: [[ 0.06154678  0.84221806  0.09623515]]
np.log(probs)[[-2.78795772 -0.17171631 -2.34096056]]
cross-entropy loss: 4.25102418183


## Gradient Decent and Back Propagation

**skip this if you want to**

We've defined the network structure and the how to penalize a universal function approximator. Now, we'll show how to make this deep thing learn.

Note: Gradient Decent and Back Propagation both require study. This will not be a complete reference.

#### Optimization

A loss function lets us gauge the quality of $W$, and thus the goal of optimization is to find a set of $W$ that minimizes the loss function. The gradient tells us the direction in which the function has the steepest rate of increase, but it does not tell us how far along this direction we should step. 
<font color="red">W hasn't been defined as a set of all possible matrices w, so saying find a set of W could be confusing. I'm assuming here that you mean an element of W instead of a set.</font>

When functions take a vector of numbers instead of a single number, these derivatives are called **partial derivatives**, and the gradient is simply the vector of partial derivatives in each dimension. <font color="red">This isn't exactly what it means to be a partial derivative. Partial derivatives are defined as derivatives of a function of multiple variables when all but the variable of interest are held fixed during the differentiation. The held fixed part is a really important part of the definition. I have tried to give a different approach below, but feel free to change it to better fit your approach. Somewhere between both of our approaches is probably best.</font>

Recall from calculus class that the derivative describes the slope of a function at a given point. When a function depends on multiple variables, the derivative must take into account all of these variables. To calculate the total derivative (taking into account all the variables) it helps to calculate partial derivatives. Partial derivatives describe how a function changes with respect to a single variable while all other variables are held constant. The partial derivative is denoted by the symbol $\partial$. Using this notation, a function $f\left(x,y\right)$ has a total derivative given by
$$
\frac{df}{dx} = \frac{\partial f}{\partial x}\frac{dx}{dx} + \frac{\partial f}{\partial y}\frac{dy}{dx}.
$$

Pretending to multiple both sides of the above equation by $dx$ gives the following. (Note that the math doesn't exactly work the same as fractions in the manner we are suggesting here, but this is an instance where pretending gets to the correct answer faster. For a more complete description refer to your preferred calculus text.)
$$
df = \frac{\partial f}{\partial x}dx + \frac{\partial f}{\partial y}dy.
$$

The equation above can be separated into the vector part describing the local slope of the function and a vector representing the infinitesimal change in each of the variables.
$$
df = \begin{bmatrix}
    \frac{\partial f}{\partial x}      & \frac{\partial f}{\partial y}
\end{bmatrix}
\begin{bmatrix}
    dx \\
    dy\\
\end{bmatrix} = \nabla \begin{bmatrix}
    dx \\
    dy\\
\end{bmatrix}
$$

The slope portion of the above equation is so frequently used that it is called the gradient, and it represents the slope of a function with respect to independent changes in the function's variables. 

Take this super basic function for example:

$f\left(x,y\right) = x y$

Calculus allows us to compute the partial derivative for either input:

$f(x,y) = x y \hspace{0.5in} \rightarrow \hspace{0.5in} \frac{\partial f}{\partial x} = y \hspace{0.5in} \frac{\partial f}{\partial y} = x$

Derivatives indicate the rate of change of a function with respect to that variable surrounding an infinitesimally small region near a particular point:

$\frac{df(x)}{dx} = \lim_{h\ \to 0} \frac{f(x + h) - f(x)}{h}$

#### Backprop via the Chain Rule

Updating our $W$ with the Chain Rule (Backprop): When you start to have complicated functions like $f(x,y,z)=(x+y)z$, you can break them down into separate functions, $q=x+y$ and $f=qz$.

Because we're interested in $f$ with respect to inputs $x, y, z$, the **chain rule** tells us the correct way to chain these gradient expressions together is with multiplication: $\frac{\partial f}{\partial x} = \frac{\partial f}{\partial q} \frac{\partial q}{\partial x}$

**Set some inputs**

$x = -2; \\
y = 5; \\
z = -4$

**Perform the forward pass**

$ q = x + y$

$f = q * z $

*q becomes 3 and f becomes -12*

**Perform the backward pass (backpropagation) in reverse order:**

**first backprop through $f = q * z$**

$\frac{\partial f}{\partial z} = q$

*gradient on z becomes 3*

$\frac{\partial f}{\partial q} = z$

*gradient on q becomes -4*

**now backprop through $q = x + y$**

$\frac{\partial f}{\partial x} = 1*\frac{\partial f}{\partial q}$

$\frac{\partial f}{\partial y} = 1*\frac{\partial f}{\partial q}$

And boom, the chain-rule

***The loss function gives the ability to evaluate $W$, the gradient tells us the sensativity of each variable with respect to the input, and the chain rule gives us the mechanism by which to update weights. Together, these three pieces form the most important parts of Deep Learning.***


It should be noted that choosing the step size (also called the learning rate) will become one of the most important (and most headache-inducing) hyperparameter settings in training a neural network
<font color="red">I think this section needs something to give a conceptual idea of backpropogation before diving into the math. Something that tells the reader that we need to walk backwards through multiple different layers using the previous layer as the goal/new loss function. Maybe an image would be helpful?</font>

In [70]:
import numpy as np
np.random.seed(1234)
# http://pytorch.org/tutorials/beginner/pytorch_with_examples.html

def ReLU(x):
    return np.maximum(0.0,x)

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6
for t in range(501):
    
    # Forward pass: compute predicted y
    h = x.dot(w1)
    h_relu = ReLU(h)
    y_pred = h_relu.dot(w2)

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    if t % 50 == 0:
        print("Loss at time step {}: {}".format(t, loss))

    # Backprop to compute gradients of w1 and w2 with respect to loss
    
    # compute grad of w2 so you can compute grad of w1
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    
    # compute grad of w1
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)

    # Update weights
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2
    
## mxnet example
#import mxnet as mx
#data = mx.symbol.Variable('data')
#fc1  = mx.symbol.FullyConnected(data = data, name='fc1', num_hidden=512)
#act1 = mx.symbol.Activation(data = fc1, name='relu1', act_type="relu")
#fc2  = mx.symbol.FullyConnected(data = act1, name = 'fc2', num_hidden = 512)
#act2 = mx.symbol.Activation(data = fc2, name='relu2', act_type="relu")
#fc3  = mx.symbol.FullyConnected(data = act2, name='fc3', num_hidden=10)
#mlp = mx.symbol.SoftmaxOutput(data=fc3, name='softmax')

# Here we instatiate the model for our data
#model = mx.mod.Module(
#    mlp,                             # Use the network we just defined
#    context = mx.cpu(0),             # Run on CPU 0
#    data_names = ['data'],           # Provide the name of 'data'
#    label_names = ['softmax_label'], # Provide the name of 'label
#    )
# Fit the model 
#model.fit(
#    train_data = training_data,
#    num_epoch = 10,
#    optimizer_params = {'learning_rate':0.1},
#    batch_end_callback = mx.callback.log_train_metric(500),
#)

Loss at time step 0: 26444892.357331783
Loss at time step 50: 15316.737116928942
Loss at time step 100: 695.3155233484949
Loss at time step 150: 59.122797880043564
Loss at time step 200: 6.4216502602055945
Loss at time step 250: 0.7720914698610868
Loss at time step 300: 0.09720175415918952
Loss at time step 350: 0.012525263136712593
Loss at time step 400: 0.0016354783492967572
Loss at time step 450: 0.00021537538297857064
Loss at time step 500: 2.8532985847947457e-05
